rgga urls update
ffoodd/a11y.css pull request #448
Opened 2022-09-11 21:38 UTC by zwiastunsw

all url's for the RGAA have been changed to the RGAA version on [tanaguru.com](https://rgaa.tanaguru.com/)

2022-09-12 06:55 UTC, ffoodd reviewed
Thanks for the PR ♥️

I think you linked the RGAA v3, however the current version is 4.1. Would you mind to update the links ?

No worry if not, I'll take care of it 🙂

2022-09-12 08:04 UTC, zwiastunsw commented
Hi, Yes, I will look into it. There are some tests that don't exist in RGAA 4, so it was simpler for me to update all the links first. Now I need to compare which tests are not there and which have changed their numbering.

2022-09-12 09:14 UTC, ffoodd commented
Thanks a lot, this is really helpful!

2023-04-07 15:17 UTC, zwiastunsw commented on sass/themes/_error.scss
> +button[class*="disabled"]:not([disabled]):not([readonly])
should be: 
button[class*="disabled"]:not([disabled], [readonly])

2023-04-07 18:35 UTC, ffoodd reviewed
Hi there, I'll keep this open until I get some time to check those links. FYI RGAA just got an update and is currently 4.1.1.

2023-04-07 21:56 UTC, zwiastunsw commented
Hi, 
These are not all the changes. 
A large group of links to wai-aria do not exist, for example in _error.scss file: 

`<https://www.w3.org/TR/wai-aria/states_and_properties#aria-checked>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#aria-checked>`
`<https://www.w3.org/TR/wai-aria/states_and_properties#aria-expanded>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#aria-expanded>`
`<https://www.w3.org/TR/wai-aria/states_and_properties#aria-controls>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#aria-controls>`
`<https://www.w3.org/TR/wai-aria/states_and_properties#aria-valuemin>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#aria-valuemin>`
`<https://www.w3.org/TR/wai-aria/states_and_properties#aria-valuemax>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#aria-valuemax>`
`<https://www.w3.org/TR/wai-aria/states_and_properties#aria-valuenow>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#aria-valuenow>`
`<https://www.w3.org/TR/wai-aria/states_and_properties#aria-orientation>` new URL in WAI-ARIA 1.2 https://www.w3.org/TR/wai-aria-1.2/#aria-orientation>`

`<https://www.w3.org/TR/wai-aria/roles#img>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#img>`
`<https://www.w3.org/TR/wai-aria/roles#presentation>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#presentation>`

`<https://www.w3.org/TR/wai-aria/roles#textalternativecomputation>` (no exist in WAI-ARIA 1.2

`<https://www.w3.org/TR/wai-aria/roles#slider>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#slider>`
`<https://www.w3.org/TR/wai-aria/roles#spinbutton>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#spinbutton>`
`<https://www.w3.org/TR/wai-aria/roles#checkbox>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#checkbox>`
`<https://www.w3.org/TR/wai-aria/roles#combobox>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#combobox>`
`<https://www.w3.org/TR/wai-aria/roles#scrollbar>` new URL in WAI-ARIA 1.2 `<https://www.w3.org/TR/wai-aria-1.2/#scrollbar>`

Once you approve and merge this PR, I will prepare another PR

2023-04-07 21:59 UTC, zwiastunsw commented on sass/themes/_error.scss
> +* <https://www.w3.org/WAI/WCAG21/Techniques/html/H5>
mistake, should be `<https://www.w3.org/WAI/WCAG21/Techniques/html/H5>`

2023-04-08 14:11 UTC, ffoodd requested changes

2023-04-08 14:11 UTC, ffoodd commented on sass/themes/_error.scss
> +* <https://www.w3.org/WAI/WCAG21/Techniques/html/H5>
```suggestion
* <https://www.w3.org/WAI/WCAG21/Techniques/html/H57>
```

2023-04-08 19:54 UTC, merged